### ISSUE TITLE
"null" is validated for a required email property

### ISSUE THREAD

**Issue by ARAtlas** [tdegrunt/jsonschema#120]
I recently updated from an older version and this issue appeared. One of the properties in my schema is a required email. undefined and "" fail the validation as expected, but null passes the validation.

Specifically, these fail, as expected:

require('jsonschema').validate(undefined, { format: 'email', required: true })
require('jsonschema').validate('', { format: 'email', required: true })

However, this passes validation, which is not expected:

require('jsonschema').validate(null, { format: 'email', required: true })

**Comment by Acubed** [comment]
The "format" keyword has some interesting semantics. From the v4 draft:

> A format attribute can generally only validate a given set of instance types. If the type of the instance to validate is not in this set, validation for this format attribute and instance SHOULD succeed.

So since the email format validates strings, non-strings will pass validation. If you want non-strings to fail validation, you can add a separate `type:"string"` constraint. Make sense?

Is there some way this could be made more clear?

**Comment by Acubed** [comment]
@ARAtlas Catch all that?

**Comment by ARAtlas** [comment]
Thank you for the explanation and the tip on constraining it to type string.
