### ISSUE TITLE
minimum value inter-dependencies 

### ISSUE THREAD

**Issue by paltanmoy** [tdegrunt/jsonschema#222]
We have a schema as below - 
```
var metricTypeEnum = ['memoryutil', 'responsetime']; 
var schema = {
    'type': 'object',
    'id':'/rules',
    'properties' : {
      'metric_type':{ 'type':'string' ,'enum':metricTypeEnum },
      'threshold':{ 'type':'number','minimum': 0},
     },
    'required' : ['metric_type','threshold']
  };
```
Now we want to specify the minimum value of threshold to be 0 if metric_type is memoryutil and to be 1 if metric_type is responsetime

What would be the best way to achieve this ?

**Comment by awwright** [comment]
@paltanmoy Sorry for the delay, you might have better luck about schema authoring on a more generic JSON Schema mailing list, check http://json-schema.org/ for help.

Your best bet would be using the `oneOf` keyword, at least until there's if/then support.

I'll close this out because it doesn't seem to be a bug or feature request, but feel free to comment, re-open, or file a new issue.
