### ISSUE TITLE
validate function is case insensitive

### ISSUE THREAD

**Issue by stefaanv** [tdegrunt/jsonschema#270]
validate function returns "true" for the below data and schema.  It should return false because "sample**d**ata" should be "sample**D**ata"
```
{
    "samples": 30,
    "remaining":  330,
    "sampledata":
    [
        [ 10587, 589465800, 21000, 1000, 70000 ], 
        [ 10588, 589466100, 21900, 1100, 70000 ], 
        [ 10606, 589471500, 22200, -13500, 62000 ]
    ]
 }
```

```
{
    "type": "object",
    "properties": {
        "samples": {
            "type": "number",
            "required": true
        },
        "remaining": {
            "type": "number",
            "required": true
        },
        "sampleData":{
            "type":"array",
            "items":{
                "type":"array",
                "items": 
                {
                    "type":"number"
                }
            }
        }
    }
}
```

**Comment by webarthur** [comment]
Try to add `additionalProperties: false` in the schema:

```
{
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "samples": {
            "type": "number",
            "required": true
        },
        "remaining": {
            "type": "number",
            "required": true
        },
        "sampleData":{
            "type":"array",
            "items":{
                "type":"array",
                "items": 
                {
                    "type":"number"
                }
            }
        }
    }
}
```

**Comment by awwright** [comment]
The correct behavior is that strings are case-sensitive. JSON Schema does not specify case-insensitive comparison like ABNF does.

Unfortunately I don't really have a good answer for how to avoid typos with incorrect character case. You can add `additionalProperties: false`, but this makes forward compatibility more difficult (the best practice for Internet protocols is to ignore fields that aren't understood, instead of raising an error).

I'll close this out since I can't discern a bug, if you can show some code alongside expected and actual output, please comment or open a new issue.
