### ISSUE TITLE
Apply different validations according to value 

### ISSUE THREAD

**Issue by avg0043** [tdegrunt/jsonschema#292]
Hi,

I have the following json:

```
{
  "name": "peter",
  "checklist": [
    {
      "type": "group",
      "shortText": {
        "initial": "hey"
      }
    },
    {
      "type": "list",
      "animals": {
        "dog": "little"
      },
      "food": [
        "apple",
        "banana"
      ]
    }
  ]
}
```
The checklist array contains different `type` elements. 
I would like to apply different validation according to the type value. For example:

- if `type = group`: I would like to apply that `shortText`is required and bla bla bla..
- if `type = list`: I would like to apply that `animals` and `food` are required and bla bla bla...

It's possible to apply different validations according to the value of the prop?

Thanks!

**Comment by awwright** [comment]
I believe this should be included as part of #307.

Additionally, take a look at the "dependencies" and "oneOf" keywords, and [this post about discriminator properties](https://stackoverflow.com/questions/61224526/how-to-represent-union-types-in-json-schema-validator/61225670#61225670).

I'm closing this out because this isn't really in the scope of this library — see https://json-schema.org/ for more information on writing a JSON Schema document. But please let me know if this answers your question.
