### ISSUE TITLE
@1.2.7 Invalid regular expression

### ISSUE THREAD

**Issue by jmsaucier** [tdegrunt/jsonschema#311]
We had regex that was validating a UUID. When upgrading to 1.2.7, that is now broken saying "Invalid escape". I think this is the commit that causes the issue: 35db08dac87a627f6e0ebcaaf72c15bfb4cf3fde

`SyntaxError: Invalid regular expression: /[0-9a-f]{8}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{12}/: Invalid escape`

And here is where we're referencing it: 

`module.exports = {
  id: 'UUID',
  type: 'string',
  description: 'Item\'s unique identifier',
  minLength: 36,
  maxLength: 36,
  pattern: '[0-9a-f]{8}\\-[0-9a-f]{4}\\-[0-9a-f]{4}\\-[0-9a-f]{4}\\-[0-9a-f]{12}',
};`

Let me know if there is anything we need to do to fix our RegEx, or possibly add an option for that unicode flag.

**Comment by awwright** [comment]
@jmsaucier I'm able to reproduce this, and I'm sort of suprised... I wasn't aware, but it appears the "u" flag not only enables Unicode characters (matching full code points instead of surrogate pairs), but it also enables some additional strict behavior, like not permitting unnecessary escapes...

The `\-` sequence you're using is an unnecessary escape, the backslash doesn't need to be escaped. You can use the following line instead:

```javascript
module.exports = { id: 'UUID', type: 'string', description: 'Item\'s unique identifier', minLength: 36, maxLength: 36, pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', };
```

The good news is this is completely compatible with other JSON Schema implementations and reverse compatible. Please let me know if that solves the issue for you.

I'll forward this on to the JSON Schema team since we're currently examining how to define regular expressions in a cross-platform way.

**Comment by jmsaucier** [comment]
@awwright Updated with that regex, and it is working. Thank you very much! 

This was validation in our DB layer and we had not set the version number of `jsonschema` to be fixed, so tests and builds started failing with the newly published version. 

I find it odd that it starts validating differently if it's unicode or not. 

I will go ahead and close this issue since my problem has been resolved.
