### ISSUE TITLE
Release Notes/CHANGELOG?

### ISSUE THREAD

**Issue by goyney** [tdegrunt/jsonschema#322]
Where does this project publish its release notes or CHANGELOGs? We've recently tried updating from `1.2.6` to `1.4.0`, which should be a non-breaking upgrade as per semver, but it breaks everything. Unfortunately, I cannot find your list of changes to determine if we need to change code on our end or report a bug.

Thank you!

**Comment by awwright** [comment]
@goyney See the milestones, https://github.com/tdegrunt/jsonschema/milestones?state=closed

However, there should be no breaking changes for valid JSON Schema objects. Please file an issue so I can take a look at it.

**Comment by goyney** [comment]
I've walked back versions: `1.4.0`, `1.3.0`, `1.2.11`, `1.2.10`, `1.2.9`, and `1.2.8`. The `1.2.7` version worked again. As I said before, we were on `1.2.6`.

Therefore, the break happened in the `1.2.7` to `1.2.8` update. There errors we seeing on `1.2.8` and higher look something like:

```
SchemaError: Expected `schema` to be an object or boolean
```

Before I try to create a smaller reproduction case, is there anything you know of that changed around that time that might be something we can look at?

**Comment by awwright** [comment]
@goyney Something's calling Validator#validate with a `schema` that's not a valid JSON Schema. Previously, an even more cryptic error would be thrown (often along the lines of `TypeError: Cannot read property 'id' of undefined`), but it's possible in some cases it would just do nothing.

**Comment by goyney** [comment]
Thank you. These errors were caught by our unit test suite. If it's possible that some cases it would do nothing, that might make sense if our mock data isn't valid schemas to begin with. We'll check that out and if we find something more out of the ordinary, I will open a separate issue with more details.

**Comment by awwright** [comment]
Yeah, if you can find the value for `schema` that wasn't throwing before, then by all means.

I don't know if there's much I'll be able to do about it, we only claim to support valid a JSON Schema.

However, I'm adding better argument checking and errors, instead of silently ignoring values that are nonsensical. I'm holding most of those for v2.

**Comment by sdurandeu** [comment]
Hi @goyney. Were you able to get to the bottom of this? We are experiencing the same issue and any pointers towards what to look would be very useful! Thanks!

**Comment by awwright** [comment]
@sdurandeu Do you have more information you can share? Do you know which values of `schema` it is that causes troubles?

**Comment by sdurandeu** [comment]
Hi @awwright. Yes, we got to the bottom of this. The issue is that we were calling the validator like this, passing a string with the schema name as in the last time:

```
const validator = new Validator();
validator.addSchema(
  {
    id: '/address',
    type: 'object',
    title: 'Address object',
    properties: {
      address: { type: 'string', notEmptyString: true, title: 'address' },
      postcode: { type: 'string', notEmptyString: true, title: 'postcode' },
    },
    required: ['address', 'postcode'],
    additionalProperties: false,
  },
  '/address',
);
const result = validator.validate(value, '/address'); --> here
```

This was working before `1.2.6`, but maybe by sheer luck? Then this check here was added which caused this same code to throw: https://github.com/tdegrunt/jsonschema/blob/master/lib/validator.js#L109

So, we've modified it to the following, which now works:

```
const result = validator.validate(value, { $ref: '/address' });
```

Hope it helps! Thanks!

**Comment by OP-Klaus** [comment]
+1 for adding a changelog. I see the milestones but it would be good to have it in the expected file format
